import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD:src/app/layout.tsx
import NavBar from "./components/NavBar";
import LandingNavBar from './components/LandingNavBar'
=======
import Sidebar from "@/components/Sidebar";

>>>>>>> 6b1653de066c0a1f9f206f3e8668160ecfb508ba:app/layout.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nerasol Payroll",
  description: "Generated by team Nerasol",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD:src/app/layout.tsx
      
        {children}
=======
     
          {children}
        
>>>>>>> 6b1653de066c0a1f9f206f3e8668160ecfb508ba:app/layout.tsx
      </body>
    </html>
  );
}
